service: my-serverless-app

provider:
 name: aws
 runtime: nodejs12.x
 memorySize: 128
 timeout: 10
 stage: production
 region: eu-central-1
 role: arn:aws:iam::453442084375:role/indian-iam-role

functions:
 api:
   handler: lambda.universal
   events:
     - http: ANY {proxy+}
     - http: ANY /